### ISSUE TITLE
New config but old one still working?

### ISSUE THREAD

**Issue by coolcat97** [Jellayy/Invitarr#10]
Hello! I saw on the readme that the config.ini got updated, but my old one here still works, is that normal??

`[bot_envs]`
`plex_user = nicetry@nicetry.lol`
`plex_pass = NICETRY`
`plex_server_name = LOLFART`
`plex_enabled = True`
`plex_roles = PlexAccess`
`plex_libs = xxx,xxx,xx,xx`

**Comment by Jellayy** [comment]
I'm like 99% sure that wouldn't work as a valid config for this version of Invitarr lol, I wonder what the logs look like when you do provide a config like that

**Comment by coolcat97** [comment]
Closing issue, was using a diff version of app.
