### ISSUE TITLE
Command to remove user from Plex and DB?

### ISSUE THREAD

**Issue by bwaco** [Jellayy/Invitarr#9]
Original invitarr had this, wondering if you guys can add

**Comment by coolcat97** [comment]
I'd love to have this as well.

@Jellayy , is there a way to view the DB in discord by chance? Or anywhere?

**Comment by coolcat97** [comment]
As the 

> I'd love to have this as well.
> 
> @Jellayy , is there a way to view the DB in discord by chance? Or anywhere?

The current command on the bottom of the readme doesn't seem to be working, the ".get_db" one

**Comment by Jellayy** [comment]
Thanks for the suggestion! `.delete_user` and `.force_delete_user` are now available as of the v2.0 update in #12

**Comment by Jellayy** [comment]
> The current command on the bottom of the readme doesn't seem to be working, the ".get_db" one

@coolcat97 

If you're still having issues with the `.get_db` command, feel free to open another issue with your container logs and I'd be able to help you out with that!
